=== MASGAU/Strings/strings.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:attribute name="name" type="xs:string"/>
  <xs:attribute name="hotkey">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:maxLength value="1" />
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>

  <xs:attribute name="type">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="label"/>
        <xs:enumeration value="title"/>
        <xs:enumeration value="message"/>
        <xs:enumeration value="tooltip"/>
        <xs:enumeration value="source"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>

  <!--complex elements-->
  <xs:element name="string">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute ref="name" />
          <xs:attribute ref="type" />
          <xs:attribute ref="hotkey" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>



  <xs:element name="strings">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="string" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:anyAttribute processContents="skip"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== MASGAU/Strings/en.xml
<?xml version="1.0" encoding="utf-8" ?>
<strings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="strings.xsd" lang="en">
  <!--  For some of these, there are pairs of strings that have the same name,
        but one will have  a type of "title" , and the other "message".
        These are for dialog boxes that are entirely translated, and should be
        translated with the thought that they will be displayed together.
        I tend to put random things, sometimes jokes, as the dialog titles,
        and if I can I like to give the message an insulting tone.
        Feel free to be clever and use your sense of humor!-->

  <!-- There are some strings that are meant to have variables inserted into them.
      They look like this:
        <string name="BackupMultipleGames">_Back These %0 Up</string> 
      The first variable will be inserted at %0, the second at %1, and so on.
      This is applicable to title/message pairs as well:
  -->

  <!-- Probably shouldn't translate this one -->
  <string name="MASGAU" type="source">MASGAU</string>
  <string name="MASGAUPortable" type="source">%MASGAU% %Portable%</string>

  <!-- General-purpose source strings -->
  <string name="Portable" type="source">Portable</string>

  <!-- Tab titles -->
  <string name="BackupRestore" type="label" hotkey="B">Backup/Restore</string>
  <string name="Monitoring" type="label" hotkey="M">Monitor</string>
  <string name="Analyzer" type="label" hotkey="A">Analyzer</string>

  
  <!-- Backup process -->
  <!-- The total # of games being processed-->
  <string name="GamesToBeBackedUpCount" type="label">%0 Games To Be Backed Up</string>
  <!-- %0: The name of the game being processed -->
  <string name="BackingUpSingleGame" type="label">Backing Up %0</string>
  <!--  %0: The name of the current game being processed
        %1: The nth game being processed
        %2: The total # of games being processed -->
  <string name="BackingUpMultipleGames" type="label">(%1/%2) Backing Up %0...</string>
  <!-- Archive Handler -->
  <!-- %0 = The name of the game owning the archive -->
  <string name="ArchiveInUseWaiting" type="label">%0 - Archive In Use, Waiting (%1/%2)</string>
  <string name="ArchiveInUseTimeout" type="title">Tired of waiting!</string>
  <string name="ArchiveInUseTimeout" type="message">The archive %0 has been unaccessible for %1 seconds, it will be skipped</string>
  <string name="SevenZipNotFound" type="title">Archiver Error</string>
  <string name="SevenZipNotFound" type="message">7z.exe Not Found In Install Folder\nYou Will Probably Need To Reinstall MASGAU</string>
  <string name="SevenZipRunError" type="title">Running is for wimps</string>
  <string name="SevenZipRunError" type="message">An error occured while trying to run 7-zip with the arguments:\n%0</string>
  <string name="RevisionCopyError" type="title">Versioning is for wusses anyway</string>
  <string name="RevisionCopyError" type="message">An error occured while trying to make a revision copy of %0</string>
  <!-- Errors -->
  <string name="NothingToBackup" type="title">It feels like there's</string>
  <string name="NothingToBackup" type="message">Nothing at all to back up</string>


  <!-- Analyzer stuff -->
  <!-- Location names - Do NOT translate these unless the folder names are legitimately different on your system!-->
  <string name="MyComputer" type="label">My Computer</string>
  <string name="ProgramFiles" type="label">Program Files</string>
  <string name="ProgramFilesX86" type="label">Program Files (x86)</string>
  <string name="MyDocuments" type="label">My Documents</string>
  <string name="SavedGames" type="label">Saved Games</string>
  <string name="VirtualStore" type="label">VirtualStore</string>
  <string name="LocalAppData" type="label">Local AppData</string>
  <string name="AppData" type="label">(Roaming) AppData</string>
  <string name="Steamapps" type="label">Steamapps</string>
  <string name="PublicUser" type="label">Public User</string>
  <string name="AllUsers" type="label">All Users/ProgramData</string>

</strings>
